name: Auto Workflow

on:
  workflow_call:
    inputs:
      version:
        description: 'Version for current release'
        required: true
        type: string
    secrets:
      token:
        required: true

env:
  USERNAME: "vishnuPratapBanki"
  TOKEN: ${{ secrets.token }}

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

#      - name: Remove Branch Protection (Unlock Branch)
#        run: |
#          curl -X DELETE \
#          -H "Accept: application/vnd.github.v3+json" \
#          -H "Authorization: Bearer ${{ secrets.token }}" \
#          https://api.github.com/repos/VishnuPratapBanki/caller/branches/main/protection

      - name: Update version.txt and Push Changes
        run: |
          git config user.email "vishnubanki@gmail.com"
          git config user.name "vishnuPratapBanki"

          git pull origin main  # Ensure latest changes

          echo "${{ inputs.version }}" > version.txt

          git add .
          git commit -m "Changed version via workflow"

          git push https://x-access-token:${{ secrets.token }}@github.com/VishnuPratapBanki/caller.git main

          cat version.txt

#      - name: Apply Branch Protection (Lock Branch)
#        run: |
#          curl -X PUT \
#          -H "Accept: application/vnd.github.v3+json" \
#          -H "Authorization: Bearer ${{ secrets.token }}" \
#          https://api.github.com/repos/VishnuPratapBanki/caller/branches/main/protection \
#          -d '{
#            "required_status_checks": {
#              "strict": true,
#              "contexts": []
#            },
#            "enforce_admins": true,
#            "required_pull_request_reviews": {
#              "dismiss_stale_reviews": true,
#              "require_code_owner_reviews": true,
#              "required_approving_review_count": 1,
#              "require_last_push_approval": true
#            },
#            "restrictions": null,
#            "required_conversation_resolution": true,
#            "required_signatures": true,
#            "allow_force_pushes": true,
#            "allow_deletions": true,
#            "lock_branch": true,
#            "required_linear_history": true,
#            "block_creations": true,
#            "allow_fork_syncing": true
#          }'