name: test

on:
  # repository_dispatch:
  #   types: [trigger-workflow]
  workflow_dispatch:
jobs:
  branch2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: echo "Building the project branch2 ..."

  deploy:
    runs-on: ubuntu-latest
    needs: branch2
    environment:
      name: staging
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to the staging environment..."
      
      - name: Await Approval for Production
        run: echo "Awaiting approval for production deployment..."
      
  final-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    environment:
      name: production
    steps:
      - name: Deploy to Production
        run: echo "Deployment to production completed!"
